default: styles/handon.scss
contrast: styles/handon-contrast.scss
mastodon-light: styles/handon-light.scss
blacklead: styles/handon-blacklead.scss
cantadark: styles/handon-cantadark.scss
vanilla-default: styles/application.scss
vanilla-contrast: styles/contrast.scss
vanilla-light: styles/mastodon-light.scss
